MD5.xs: eliminate C++ guards
These aren't needed with modern perls, and it's only useful to
build modern perls as C++.

This was causing an error in a system header when building blead
as C++ with MSVC:

    C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um\wspiapi.h(53):
    error C2894: templates cannot be declared to have 'C' linkage

See https://github.com/Perl/perl5/issues/21073 for more information